import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/app/common/AppSidebar';
import { ThemeProvider } from '@/components/ui/theme-provider';
import { SiteHeader } from '@/components/ui/site-header';
import StoreProvider from '@/app/store/StoreProvider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            suppressHydrationWarning
        >
            <body
                className={`${geistSans.variable} ${geistMono.variable} font-sans`}
                style={{
                    fontFamily: 'var(--font-geist-sans)',
                }}
            >
                <StoreProvider>
                    <ThemeProvider
                        attribute='class'
                        defaultTheme='system'
                        enableSystem
                        disableTransitionOnChange
                    >
                        <SidebarProvider>
                            <AppSidebar />
                            <SidebarInset>
                                <SiteHeader />
                                {children}
                            </SidebarInset>
                        </SidebarProvider>
                    </ThemeProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
